id: I7F687FFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T08:53:44+00:00'
last_modified: '2022-06-10T09:53:40.674692+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22130
  title: གསུང་འབུམ། བཞད་པའི་རྡོ་རྗེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E490:
      image_group_id: I5888
      title: ''
      total_pages: 752
      order: 1
      base_file: E490.txt
    FD5A:
      image_group_id: I5889
      title: ''
      total_pages: 588
      order: 2
      base_file: FD5A.txt
    E67B:
      image_group_id: I5890
      title: ''
      total_pages: 604
      order: 3
      base_file: E67B.txt
    094D:
      image_group_id: I5891
      title: ''
      total_pages: 528
      order: 4
      base_file: 094D.txt
    2E4C:
      image_group_id: I5892
      title: ''
      total_pages: 476
      order: 5
      base_file: 2E4C.txt
    EAA4:
      image_group_id: I5893
      title: ''
      total_pages: 432
      order: 6
      base_file: EAA4.txt
    F6F5:
      image_group_id: I5894
      title: ''
      total_pages: 428
      order: 7
      base_file: F6F5.txt
    C879:
      image_group_id: I5895
      title: ''
      total_pages: 556
      order: 8
      base_file: C879.txt
    24C3:
      image_group_id: I5896
      title: ''
      total_pages: 550
      order: 9
      base_file: 24C3.txt
    E65B:
      image_group_id: I5897
      title: ''
      total_pages: 510
      order: 10
      base_file: E65B.txt
    DCBD:
      image_group_id: I5898
      title: ''
      total_pages: 506
      order: 11
      base_file: DCBD.txt
    AE99:
      image_group_id: I5899
      title: ''
      total_pages: 624
      order: 12
      base_file: AE99.txt
    FE9F:
      image_group_id: I5900
      title: ''
      total_pages: 520
      order: 13
      base_file: FE9F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
